server.port: 9090

spring:
  profiles: default
  data:
    mongodb:
      host: localhost
      port: 27017
      database: order

app:
  upstream:
    wirecard:
      uri: https://mock.com
      token: WIRECARD_TOKEN
      key: WIRECARD_KEY

logging:
  config: classpath:logback-spring.xml
  level:
    org.springframework: DEBUG
    zoret4: DEBUG

---

spring:
  profiles: stage

app:
  upstream:
    wirecard.uri: https://sandbox.moip.com.br/v2

---

spring:
  profiles: prod

