server.port: 8780

spring:
  profiles: default
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: order
  application:
    name: all-about-money::order

app:
  upstream:
    wirecard:
      name: WIRECARD
      uri: https://mock.com
      token: ${WIRECARD_TOKEN}
      key: ${WIRECARD_KEY}
      preferences.notifications:
        -
          name  : ORDER
          target: ${VENDOR_CALLBACK_ORDER_EVENTS:http://localhost:8780/wirecard/orders/event}
          events:
            - ORDER.PAID
            - ORDER.NOT_PAID
            - ORDER.REVERTED
        -
          name  : PAYMENT
          target: ${VENDOR_CALLBACK_PAYMENT_EVENTS:http://localhost:8780/wirecard/payments/event}
          events:
            - PAYMENT.*

logging:
  config: classpath:logback-spring.xml
  level:
    org.springframework: DEBUG
    zoret4: DEBUG
  path: /tmp

---

spring:
  profiles: stage

app:
  upstream:
    wirecard.uri: https://sandbox.moip.com.br/v2

---

spring:
  profiles: prod

